Fixes/navbar
HackRU/frontend pull request #300
Opened 2020-02-23 18:38 UTC by ryanmao725

Attempting to address #293

2020-02-23 18:45 UTC, thekabistro requested changes

2020-02-23 18:45 UTC, thekabistro commented on src/NavBar.jsx
> +                    className={keys[i] === "ABOUT" && window.innerWidth < 768 ? "pt-3" : ""}>
Make this more generic by using  i=0?   Its not always the about page at the top of the drawer

2020-02-23 18:55 UTC, shivanmodha requested changes
Doesn't appear to work here:
![image](https://user-images.githubusercontent.com/29020430/75117963-16e39580-5644-11ea-8fd7-a8e2c8500755.png)

2020-02-23 18:55 UTC, shivanmodha commented on src/NavBar.jsx
> +                    className={i = 0 && window.innerWidth < 768 ? "pt-3" : ""}>
`i === 0`

2020-02-23 18:58 UTC, ryanmao725 commented on src/NavBar.jsx
> +                    className={i = 0 && window.innerWidth < 768 ? "pt-3" : ""}>
ah fuck

2020-02-23 18:58 UTC, shivanmodha commented on src/NavBar.jsx
> +                    className={i = 0 && window.innerWidth < 768 ? "pt-3" : ""}>
xD

2020-02-23 19:39 UTC, shivanmodha commented
Can you get this to work with the home as well?

2020-02-24 20:27 UTC, shivanmodha approved these changes
LGTM! 4th times the charm ay?

2020-02-24 20:27 UTC, merged