Pagination
HackRU/frontend pull request #382
Opened 2020-11-02 00:43 UTC by GabrielWeinbrenner

2020-11-02 21:26 UTC, shivanmodha requested changes
Overall pretty good, see comments below. Overall, let's just remove the modal code for now, we can handle it in another PR.

2020-11-02 21:26 UTC, shivanmodha commented on src/components/Dashboard/TeamViewer.jsx
> +// };
Do we need this, or can we remove? We can add in the more details per team in another PR

2020-11-02 21:26 UTC, shivanmodha commented on src/components/Dashboard/TeamViewer.jsx
> +            console.log(success.response);
We should probably remove these console logs

2020-11-02 21:26 UTC, shivanmodha commented on src/components/Dashboard/TeamViewer.jsx
> +        <>
Do we need to nest this in a `<>` tag? Can we just make the `<Grid>` the root element?

2020-11-02 21:26 UTC, shivanmodha commented on src/components/Dashboard/TeamViewer.jsx
> +                                // }}
Same with this--let's remove this for now, and we'll add in the more details in another release

2020-11-02 21:26 UTC, shivanmodha commented on src/components/Profile.js
> -    leave: "/leave",
Why do some of these have `TEAMRU_BASE + /<endpoint>` and some of these have just `/<endpoint`? Can we make these a bit more consistent?

2020-11-02 21:32 UTC, zain08816 commented on src/components/Profile.js
> -    leave: "/leave",
Yeah, the reasoning for this is that some of the URLs are something like TeamRU_Base+/endpoint then some are TeamRU_Base/endpoint + /team_id + /endpoint. This is mostly for teams where you have /teams, /teams/teamid, /teams/teamid/invite, /teams/teamid/reject, etc. we can probably make this more consistent by using format codes.

2020-11-02 22:33 UTC, shivanmodha commented on src/components/Profile.js
> -    leave: "/leave",
In that case, are there any template things that we can do with the string? Something like
```
TEAMRU_BASE + "/teams/${Id}/leave"?
```
Might have to make it a function, unless if JS has an equivalent to pythons `.format` method.

Reason is so that the endpoint are clear when you look at this one object. It's either generator url or the actual url. What are your thoughts?

2020-11-02 23:05 UTC, zain08816 commented on src/components/Profile.js
> -    leave: "/leave",
@shivanmodha I made a change to how it is, lmk what you think

2020-11-02 23:23 UTC, shivanmodha commented on src/components/Profile.js
> -    leave: "/leave",
I guess that works

2020-11-04 06:19 UTC, shivanmodha commented
Merging this in

2020-11-04 06:19 UTC, merged